package com.teamchallenge.easybuy.cart;

import com.teamchallenge.easybuy.cart.entity.ShoppingCartItem;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import lombok.Builder;

import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.Set;
import java.util.UUID;

@Builder
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
/**
 * Shopping cart aggregate for a user.
 */
@Entity
@Table(name = "shopping_cart")
@Schema(description = "Customer shopping cart with selected items")
public class ShoppingCart {

    /** Unique shopping cart identifier. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Schema(description = "Shopping cart ID", accessMode = Schema.AccessMode.READ_ONLY)
    private UUID id;

    /** Owner user identifier. */
    @Column(name = "user_id", nullable = false)
    @Schema(description = "Owner user ID", requiredMode = Schema.RequiredMode.REQUIRED)
    private UUID userId;

    /** Item rows that belong to this cart. */
    @OneToMany(mappedBy = "shoppingCart",
            cascade = {CascadeType.PERSIST, CascadeType.MERGE,
                    CascadeType.REFRESH, CascadeType.REMOVE, CascadeType.DETACH},
            orphanRemoval = true,
            fetch = FetchType.EAGER)
    @Schema(description = "Shopping cart line items")
    private Set<ShoppingCartItem> items;

    /** Persisted counter of distinct item rows in the cart. */
    @Column(name = "items_quantity", nullable = false)
    @Schema(description = "Number of distinct cart items", requiredMode = Schema.RequiredMode.REQUIRED)
    private Integer itemsQuantity;

    /** Persisted counter of total goods quantity in the cart. */
    @Column(name = "goods_quantity", nullable = false)
    @Schema(description = "Total goods quantity in cart", requiredMode = Schema.RequiredMode.REQUIRED)
    private Integer goodsQuantity;

    /** Creation timestamp generated by persistence layer. */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    @Schema(description = "Creation timestamp", accessMode = Schema.AccessMode.READ_ONLY)
    private OffsetDateTime createdAt;

    /** Cart closing timestamp if the cart was completed/closed. */
    @Column(name = "closed_at")
    @Schema(description = "Cart closing timestamp")
    private OffsetDateTime closedAt;

    public static final int DEFAULT_PRODUCTS_QUANTITY = 0;

    /**
     * Calculates the current number of distinct item rows from {@code items}.
     *
     * @return number of distinct cart items
     */
    public Integer getItemsQuantity() {
        return this.items.size();
    }

    /**
     * Calculates total goods quantity as a sum of all item quantities.
     *
     * @return total goods quantity or {@value #DEFAULT_PRODUCTS_QUANTITY} when cart has no items
     */
    public Integer getProductsQuantity() {
        return this.items.stream()
                .map(ShoppingCartItem::getGoodsQuantity)
                .reduce(Integer::sum)
                .orElse(DEFAULT_PRODUCTS_QUANTITY);
    }

    @Override
    public boolean equals(Object object) {
        if (this == object)
            return true;
        if (object == null || getClass() != object.getClass())
            return false;
        ShoppingCart that = (ShoppingCart) object;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return "ShoppingCart {" +
                "id = " + id +
                '}';
    }
}
